matrix:
  include:
  - language: node_js
    node_js:
    - '10'
    cache:
      directories:
      - node_modules
    install:
    - rm -rf node_modules/*/.git/
    - npm install -q --no-color --no-progress
    before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
      > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - "./cc-test-reporter before-build"
    script:
    - npm run test -- --coverage --watchAll=false
    after_script:
    - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
  - dist: trusty
    stage: build and deploy docker image
    services:
    - docker
    if: tag IS present
    env:
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=okhalid/eop
    before_install:
    - wget -qO- https://toolbelt.heroku.com/install.sh | sh
    - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
    - echo "$HEROKU_API_KEY" | docker login -u "$HEROKU_USER" --password-stdin registry.heroku.com
    script:
    - docker build -f heroku/Dockerfile -t $REPO:$COMMIT .
    - docker tag $REPO:$COMMIT $REPO:latest
    - docker tag $REPO:$COMMIT $REPO:$TRAVIS_TAG
    - docker tag $REPO:$COMMIT $REPO:$TRAVIS_TAG
    - docker tag $REPO:$COMMIT registry.heroku.com/$HEROKU_APP_NAME/web
    - docker push $REPO
    - docker push registry.heroku.com/$HEROKU_APP_NAME/web
    - heroku container:release web --app $HEROKU_APP_NAME
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: WVVIQeoFLk/B/XzCmUbAQCbRCSaHIurbDm1wl+J3dqla4KaQo3REW2njP10Bvw07iJlYs8WM1o/J1lMlEfD6JnqOXQ2bQ37/rcAfApUrccmp/J1cHvG/8PiZllO4b8L+68yf9YPBscG9KDbR+JjFNqQjy+crKkZS27S/9ez4DTkt9K/Lgo86Of/p64NWiwG9dFqfwAq/X7HyUXeedN8uOq7xvN0cSXfh8HeHH6Z3CKCy9GX2brgiczPwjqiksLJjtPEcN6P5Yg7jWjM4IQB03e+1v6eGgHbYNZNLPwrbEcUpCdhitinlrYj04KHpNAhA4UTNcTTpQ7dlvDE3L1VpBwPnl32qiT0VMqbTGoKHQo25BYtnW5ah0Ri49wYZReYUiusHNkrT8Krc015EOoMuQcxV2htj8Fk2SDPkoLtbuBzjRZaUOr0pHiJStm/bfcZHcJrJk3SBEru7SR+mNQMSmge4l4zrBT6o/P/Kf4tFAaSv3S6RG6z5hJwMlYPQvi8mMIr2ztOsaXj5+omBjymDxHJExkjucBNAyk6RLZSIfMz4/Zu3RSNrTdDNModH2hIBcb8/k0NsqcuTy5GoJVJflRc+5Q8XeeOxNTaK9VwXO1icmAZaEwCe8JuJXqE+JlIDsSGWS9VuFdwh8R+mHayWG1xq4aZlmJ4/PRloBIJV80I=
  app: elevation-of-privilege
  on:
    repo: Mich-b/elevation-of-privilege
  skip_cleanup: true
